version: "3.9"
services:
  auth:
    build: ./auth
    ports:
      - "3001:3001"
    # environment:
      # - DB_URI=mongodb://user-db:27017/userdb
    depends_on:
      - auth-db
    environment:
      - MONGO_URI=mongodb://auth-db:27017/authdb

  post:
    build: ./post
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://post-db:27017/postdb
      # - MINIO_ENDPOINT=http://minio:9000
      # - MINIO_ACCESS_KEY=rootadmin
      # - MINIO_SECRET_KEY=rootadmin
      # - MINIO_BUCKET_NAME=post-service-bucket
    depends_on:
      - notif-db
      - auth-db
      - post-db
      - minio

  notification:
    build: ./notification
    ports:
      - "5003:5003"
    environment:
      - MONGO_URI=mongodb://notif-db:27017/notifdb
    depends_on:
      - notif-db
      - auth-db
      - post-db
   

  gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth
      - post
      - notification

  # MinIO for object storage
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001" 
    environment:
      - MINIO_ROOT_USER=rootadmin
      - MINIO_ROOT_PASSWORD=rootadmin
    volumes:
      - minio-data:/data

  # Separate MongoDB containers for each service
  auth-db:
    image: mongo:latest
    container_name: auth-db
    ports:
      - "27017:27017"
    volumes:
      - auth-data:/data/db

  post-db:
    image: mongo:latest
    container_name: post-db
    ports:
      - "27018:27017"
    volumes:
      - post-data:/data/db

  notif-db:
    image: mongo:latest
    container_name: notif-db
    ports:
      - "27019:27017"
    volumes:
      - notif-data:/data/db

volumes:
  auth-data:
  post-data:
  notif-data:
  minio-data: